# Generated by Django 5.1.1 on 2025-01-28 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProgramacionPagos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cuenta', models.CharField(max_length=16)),
                ('NIT', models.CharField(max_length=20)),
                ('Sucursal', models.IntegerField(blank=True, null=True)),
                ('Documento', models.CharField(max_length=15)),
                ('Fecha', models.DateField()),
                ('FechaVence', models.DateField()),
                ('FechaRecibo', models.DateField(blank=True, null=True)),
                ('FechaReenvio', models.DateField(blank=True, null=True)),
                ('FechaPago', models.DateField(blank=True, null=True)),
                ('FechaCreado', models.DateTimeField(auto_now_add=True)),
                ('Debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('Credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('RetencionCausada', models.IntegerField(blank=True, null=True)),
                ('Paga', models.IntegerField(blank=True, null=True)),
                ('CtaCobro', models.IntegerField(blank=True, null=True)),
                ('Prefijo', models.CharField(max_length=5)),
                ('Registro', models.IntegerField(blank=True, null=True)),
                ('PrioridadAlta', models.BooleanField(default=False, verbose_name='Alta urgencia (Rojo)')),
                ('PrioridadMedia', models.BooleanField(default=False, verbose_name='Mitad de mes (Amarillo)')),
                ('PrioridadBaja', models.BooleanField(default=False, verbose_name='Final de mes (Azul)')),
                ('PrioridadInmediata', models.BooleanField(default=False, verbose_name='Pago inmediato (Verde)')),
                ('UsuarioAsignador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facturas_programacion_pagos',
                'managed': True,
            },
        ),
    ]
