# Generated by Django 5.1.1 on 2025-01-29 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='FechaComitePago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
