# Generated by Django 5.1.1 on 2025-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0002_facturaprogramacionpagos_fechacomitepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaprogramacionpagos',
            name='FechaCreado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
