# Generated by Django 5.1.1 on 2025-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0003_alter_facturaprogramacionpagos_fechacreado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaprogramacionpagos',
            name='FechaComitePago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
