# Generated by Django 5.1.1 on 2025-01-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0004_alter_facturaprogramacionpagos_fechacomitepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='NombreCuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='NombreNit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='NumeroEgreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='PagoTesoreria',
            field=models.BooleanField(default=False, verbose_name='Pago por tesorería'),
        ),
    ]
