# Generated by Django 5.1.1 on 2025-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0005_facturaprogramacionpagos_nombrecuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='RevisionFinanciera',
            field=models.BooleanField(default=False),
        ),
    ]
