# Generated by Django 5.1.1 on 2025-01-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacionpagos', '0006_facturaprogramacionpagos_revisionfinanciera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaprogramacionpagos',
            old_name='NombreCuenta',
            new_name='CuentaNombre',
        ),
        migrations.AddField(
            model_name='facturaprogramacionpagos',
            name='CuentaNit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
