version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - /media/disco1/examenes:/media/disco1/examenes
      - /media/disco1/:/neuro
      - /mnt/prueba:/mnt/prueba:rw

      

