# Generated by Django 4.2 on 2024-11-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('cups', models.CharField(max_length=10)),
                ('tipo_examen', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
