# Generated by Django 4.2 on 2025-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultadosgedocumental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idcita', models.IntegerField(unique=True, verbose_name='ID de la Cita')),
                ('Admision', models.IntegerField(verbose_name='Número de Admisión')),
                ('FechaCita', models.DateTimeField(verbose_name='Fecha de la Cita')),
                ('IdMedico', models.CharField(max_length=20, verbose_name='ID del Médico')),
                ('NombreMedico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Medico')),
                ('NumeroPaciente', models.IntegerField(verbose_name='Número de Paciente')),
                ('Cups', models.CharField(max_length=20, verbose_name='Código CUPS')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('NombreCompleto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo')),
                ('CodigoEntidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Entidad')),
                ('ResultadoArchivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado de Archivos')),
                ('DescripcionCups', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción CUPS')),
            ],
            options={
                'db_table': 'consolidado_estudios',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
    ]
