# Generated by Django 4.2 on 2024-11-23 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gedocumental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionsinarchivo',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacionesarchivos',
            name='IdArchivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Observaciones', to='gedocumental.archivofacturacion'),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='UsuarioCuentasMedicas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_medicas_archivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='UsuariosTesoreria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesoreria_archivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
