# Generated by Django 4.2 on 2025-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='TipoHallazgo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Hallazgo'),
        ),
    ]
