# Generated by Django 4.2.20 on 2026-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstudioSueno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(verbose_name='Fecha de realización')),
                ('equipo', models.CharField(choices=[('ESTUDIOS 1', 'ESTUDIOS 1'), ('ESTUDIOS 2', 'ESTUDIOS 2'), ('ESTUDIOS 3', 'ESTUDIOS 3'), ('ESTUDIOS 4', 'ESTUDIOS 4'), ('ESTUDIOS 5', 'ESTUDIOS 5'), ('ESTUDIOS 6', 'ESTUDIOS 6'), ('ESTUDIOS 7', 'ESTUDIOS 7'), ('ESTUDIOS 8', 'ESTUDIOS 8'), ('ESTUDIOS 9', 'ESTUDIOS 9')], max_length=20, verbose_name='Equipo')),
                ('nombres_completos', models.CharField(max_length=255, verbose_name='Nombre del paciente')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='Número de documento')),
                ('estudio_realizado', models.CharField(choices=[('EEG ADULTO', 'EEG ADULTO'), ('EEG PEDIATRICO', 'EEG PEDIATRICO'), ('PSG ADULTO', 'PSG ADULTO'), ('PSG BPAP', 'PSG BPAP'), ('PSG CPAP', 'PSG CPAP'), ('PSG OXIMETRÍA', 'PSG OXIMETRÍA'), ('PSG OXIMETRÍA PEDIATRICA', 'PSG OXIMETRÍA PEDIATRICA'), ('PSG PEDIATRICA CPAP', 'PSG PEDIATRICA CPAP'), ('PSG PEDIATRICA OXIMETRÍA', 'PSG PEDIATRICA OXIMETRÍA'), ('VTLM 2 HORAS PEDIATRICA', 'VTLM 2 HORAS PEDIATRICA'), ('VTLM 3 HORAS ADULTO', 'VTLM 3 HORAS ADULTO'), ('VTLM 3 HORAS PEDIATRICA', 'VTLM 3 HORAS PEDIATRICA'), ('VTLM 4 HORAS ADULTO', 'VTLM 4 HORAS ADULTO'), ('VTLM 4 HORAS PEDIATRICA', 'VTLM 4 HORAS PEDIATRICA'), ('VTLM 5 HORAS ADULTO', 'VTLM 5 HORAS ADULTO'), ('VTLM 6 HORAS ADULTO', 'VTLM 6 HORAS ADULTO'), ('VTLM 6 HORAS PEDIATRICA', 'VTLM 6 HORAS PEDIATRICA'), ('VTLM 8 HORAS ADULTO', 'VTLM 8 HORAS ADULTO'), ('VTLM 8 HORAS PEDIATRICA', 'VTLM 8 HORAS PEDIATRICA'), ('VTLM 12 HORAS ADULTO', 'VTLM 12 HORAS ADULTO'), ('VTLM 12 HORAS PEDIATRICA', 'VTLM 12 HORAS PEDIATRICA'), ('VTLM 24 HORAS ADULTO', 'VTLM 24 HORAS ADULTO'), ('VTLM 24 HORAS PEDIATRICA', 'VTLM 24 HORAS PEDIATRICA'), ('VTLM 48 HORAS ADULTO', 'VTLM 48 HORAS ADULTO'), ('VTLM 48 HORAS PEDIATRICA', 'VTLM 48 HORAS PEDIATRICA'), ('VTLM 72 HORAS', 'VTLM 72 HORAS')], max_length=60, verbose_name='Estudio realizado')),
                ('especialista', models.CharField(max_length=255, verbose_name='Especialista')),
                ('entidad', models.CharField(blank=True, max_length=255, verbose_name='Entidad')),
                ('tecnico', models.CharField(max_length=255, verbose_name='Técnico')),
                ('lectura_examen', models.BooleanField(default=False, verbose_name='Lectura examen')),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'registro_estudio_sueno',
                'ordering': ['-fecha_realizacion'],
            },
        ),
    ]
